version: '3'
services:
  db:
    image: mysql:8.0.37
    container_name: gajang-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 9001:3306
    networks:
      - gajang-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002-9004:8080
    depends_on:
      - db
    networks:
      - gajang-net

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9005-9007:8080
    depends_on:
      - db
    networks:
      - gajang-net

networks:
  gajang-net:
    driver: bridge
